dierentheater/urls.py
#  Dieren Theater - lachambre.be to json sausage machine
#  Copyright (C) 2011  Laurent Peuch <cortex@worlddomination.be>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import patterns, include, url
from django.views.generic import TemplateView

from tastypie.api import Api
from lachambre.api import DeputyResource, PartyResource, CommissionMembershipRessource, CommissionResource, DocumentResource, WrittenQuestionResource, AnnualReportRessource

v1_api = Api(api_name='v1')
v1_api.register(AnnualReportRessource())
v1_api.register(DeputyResource())
v1_api.register(PartyResource())
v1_api.register(CommissionResource())
v1_api.register(CommissionMembershipRessource())
v1_api.register(DocumentResource())
v1_api.register(WrittenQuestionResource())

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name="home.html"), name='home'),
    url(r'^lachambre/', include('lachambre.urls', namespace='deputies')),
    url(r'^api/', include(v1_api.urls)),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # url(r'^admin/', include(admin.site.urls)),
)

lachambre/urls.py
#  Dieren Theater - lachambre.be to json sausage machine
#  Copyright (C) 2011  Laurent Peuch <cortex@worlddomination.be>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import patterns, url
from django.views.generic import ListView, DetailView

from models import Deputy, Party, Commission, Document, Question, Analysis, WrittenQuestion, AnnualReport, CommissionMembership

urlpatterns = patterns('',
    url(r'^deputy/$', ListView.as_view(queryset=Deputy.objects.all()), name='deputy-list'),
    # yes, O in the regex, one deputy has an O instead of a 0 in it's lachambre_id, yes this is awfull
    url(r'^deputy/(?P<slug>[O0-9]+)/$', DetailView.as_view(queryset=Deputy.objects.all(), slug_field="lachambre_id"), name='deputy'),
    url(r'^party/$', ListView.as_view(queryset=Party.objects.all()), name='party-list'),
    url(r'^party/(?P<pk>[-a-zA-Z0-9]+)/$', DetailView.as_view(queryset=Party.objects.all(), slug_field="lachambre_id"), name='party'),
    url(r'^commission/$', ListView.as_view(queryset=Commission.objects.all()), name='commission-list'),
    url(r'^commission/(?P<slug>[0-9]+)/$', DetailView.as_view(queryset=Commission.objects.all(), slug_field="lachambre_id"), name='commission'),
    url(r'^commission-membership/$', ListView.as_view(queryset=CommissionMembership.objects.all()), name='commission-membership-list'),
    url(r'^commission-membership/(?P<pk>[-a-zA-Z0-9]+)/$', DetailView.as_view(queryset=CommissionMembership.objects.all()), name='commission-membership'),
    url(r'^document/$', ListView.as_view(queryset=Document.objects.all()), name='document-list'),
    url(r'^document/(?P<slug>[0-9]+)/$', DetailView.as_view(queryset=Document.objects.all(), slug_field="lachambre_id"), name='document'),
    url(r'^written-question/$', ListView.as_view(queryset=WrittenQuestion.objects.all()), name='written-question-list'),
    url(r'^written-question/(?P<slug>[-a-zA-Z0-9]+)/$', DetailView.as_view(queryset=WrittenQuestion.objects.all(), slug_field="lachambre_id"), name='written-question'),
    url(r'^question/$', ListView.as_view(queryset=Question.objects.all()), name='question-list'),
    url(r'^question/(?P<slug>[A-Z0-9]+)/$', DetailView.as_view(queryset=Question.objects.all(), slug_field="lachambre_id"), name='question'),
    url(r'^analysis/$', ListView.as_view(queryset=Analysis.objects.all()), name='analysis-list'),
    url(r'^analysis/(?P<slug>[A-Z0-9]+)/$', DetailView.as_view(queryset=Analysis.objects.all(), slug_field="lachambre_id"), name='analysis'),
    url(r'^annual-report/$', ListView.as_view(queryset=AnnualReport.objects.all()), name='annual-report-list'),
    url(r'^annual-report/(?P<pk>[-a-zA-Z0-9]+)/$', DetailView.as_view(queryset=AnnualReport.objects.all()), name='annual-report'),
)

lachambre/models.py
# encoding: utf-8

#  lachambre.be to json sausage machine
#  Copyright (C) 2011  Laurent Peuch <cortex@worlddomination.be>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

import re
import sys
import traceback
import logging
logger = logging.getLogger('')

from BeautifulSoup import BeautifulSoup
from lxml import etree

from json import dumps
from datetime import datetime
from bs4 import NavigableString
from django.db import models
from djangotoolbox.fields import ListField, EmbeddedModelField, DictField

from scraper import scraper
from scraper.utils import (LACHAMBRE_PREFIX, get_or_create,
                           AccessControlDict, get_href_else_blank,
                           get_items_list_else_empty_list, dico_get_text,
                           get_text_else_blank, update_or_create,
                           DOSSIER_ID_REGEX, clean_text,
                           Parsable)

from .documents_parsing_utils import document_pdf_part_cutter, document_to_dico
from .tasks import app


class Jsonify(object):
    def json(self):
        data = self.__class__.objects.filter(pk=self.pk).values()[0]
        if "creation_datetime" in data:
            del data["creation_datetime"]
        if "current" in data:
            del data["current"]
        return dumps(data, indent=4)


class Deputy(models.Model, Jsonify, Parsable):
    current = models.BooleanField(default=True)
    creation_datetime = models.DateTimeField(default=datetime.now)
    full_name = models.CharField(max_length=1337)
    first_name = models.CharField(max_length=1337)
    last_name = models.CharField(max_length=1337)
    sex = models.CharField(max_length=1337, null=True)
    emails = ListField()
    party = models.ForeignKey('Party', null=True)
    url = models.CharField(max_length=1337)
    websites = ListField()
    lachambre_id = models.CharField(max_length=1337)
    language = models.CharField(max_length=1337, null=True)
    cv = DictField()
    photo_uri = models.CharField(max_length=1337)

    @classmethod
    def fetch_list(klass, cache=False, sync=False):
        soup = scraper.get("http://www.lachambre.be/kvvcr/showpage.cfm?section=/depute&language=fr&rightmenu=right_depute&cfm=/site/wwwcfm/depute/cvlist.cfm", "deputies", cache=cache, sync=sync)

        for dep in soup.table('tr'):
            items = dep('td')
            url = items[0].a['href']
            lachambre_id = re.search('key=([0-9O]+)', url).groups()[0]

            deputy = Deputy.objects.filter(lachambre_id=lachambre_id)
            full_name = re.sub(" +", " ", items[0].a.text.strip())

            if not deputy:
                logger.info("[NEW] deputy: %s" % full_name)
            deputy = deputy[0] if deputy else Deputy(lachambre_id=lachambre_id)

            if items[1].a.text.strip():
                deputy.party = get_or_create(Party, name=items[1].a.text.strip(), url=dict(items[1].a.attrs)['href'])

            email = items[2].a.text
            website = items[3].a['href'] if items[3].a else None

            if email not in deputy.emails:
                deputy.emails.append(email)
            if website not in deputy.websites:
                deputy.websites.append(website)

            deputy.full_name = full_name
            deputy.url = url
            deputy.save()

        tasks = []

        for index, deputy in enumerate(list(Deputy.objects.all())):
            logger.debug("%s %s" % (index, deputy.full_name))
            if sync:
                klass.fetch_one(deputy, cache=cache, sync=sync)
            else:
                klass.fetch_one.delay(deputy, cache=cache, sync=sync)

        if not sync:
            map(lambda x: x.get, tasks)

    @classmethod
    def fetch_one(klass, deputy, cache=False, sync=False):
        soup, suppe = scraper.get_with_nl(LACHAMBRE_PREFIX + deputy.url, deputy.full_name, cache=cache, sync=sync)

        deputy.photo_uri = "http://www.lachambre.be" + soup.table.img["src"]
        # XXX can't get this anymore I guess :(
        # deputy.language = soup.table.i.parent.text.split(":")[1] if soup.i else None
        deputy.cv["fr"] = re.sub('  +', ' ', soup('table')[1].p.text).strip()
        deputy.cv["nl"] = re.sub('  +', ' ', suppe('table')[1].p.text).strip()
        if deputy.cv["fr"].encode("Utf-8").startswith("Députée"):
            deputy.sex = "F"
        elif deputy.cv["fr"].encode("Utf-8").startswith("Député"):
            deputy.sex = "M"
        else:
            deputy.sex = None

        Deputy.split_deputy_full_name(deputy, soup)
        deputy.save()

    @staticmethod
    def split_deputy_full_name(deputy, soup):
        return
        # stupid special case
        from ipdb import set_trace
        set_trace()
        if deputy.full_name == "Fernandez Fernandez Julie":
            deputy.first_name = "Julie"
            deputy.last_name = "Fernandez Fernandez"
        elif deputy.full_name == "Dedecker Jean Marie":
            deputy.first_name = "Jean Marie"
            deputy.last_name = "Dedecker"
        # here we guess the first and last name, for that we compare
        # deputy.full_name that is in the form of "de Donnea
        # François-Xavier" and the name of the deputy page which is in the
        # form of "François-Xavier de Donnea"
        elif len(deputy.full_name.split(" ")) > 2:
            it = 0
            while it < len(deputy.full_name.split(" ")):
                if soup.h2.text.split(" ")[it] != deputy.full_name.split(" ")[-(it + 1)]:
                    break
                it += 1
                logger.debug("%s %s %s" % (it, soup.h2.text.split(" ")[it], deputy.full_name.split(" ")[-(it + 1)]))
            if not it:
                raise Exception
            deputy.first_name = " ".join(soup.h2.text.split(" ")[:it]).strip()
            deputy.last_name = " ".join(soup.h2.text.split(" ")[it:]).strip()
            logger.debug("%s %s" % ([deputy.first_name], [deputy.last_name]))
        else:
            # if there is only 2 words just split this in 2
            deputy.first_name = deputy.full_name.split(" ")[1].strip()
            deputy.last_name = deputy.full_name.split(" ")[0].strip()
            logger.debug("%s %s" % ([deputy.first_name], [deputy.last_name]))



    def __unicode__(self):
        return '%s - %s' % (self.full_name, self.party)

    class Meta:
        ordering = ["full_name"]

    class MongoMeta:
        indexes = [
            [("lachambre_id", 1)]
        ]

    def get_url(self):
        return LACHAMBRE_PREFIX + self.url if not self.url.startswith("http") else self.url


Deputy.fetch_list = app.task(Deputy.fetch_list)
Deputy.fetch_one = app.task(Deputy.fetch_one)


class Party(models.Model, Jsonify):
    current = models.BooleanField(default=True)
    creation_datetime = models.DateTimeField(default=datetime.now)
    name = models.CharField(max_length=1337)
    url = models.URLField()


    def __unicode__(self):
        return self.name

    def get_url(self):
        return LACHAMBRE_PREFIX + self.url if not self.url.startswith("http") else self.url

    class Meta:
        ordering = ["name"]


class Commission(models.Model, Jsonify, Parsable):
    current = models.BooleanField(default=True)
    creation_datetime = models.DateTimeField(default=datetime.now)
    lachambre_id = models.IntegerField()
    name = DictField()
    full_name = DictField()
    url = models.URLField()
    type = DictField()
    deputies = ListField(models.ForeignKey("CommissionMembership"))
    seats = DictField()

    @classmethod
    def fetch_list(klass, cache=False, sync=False):
        soup, suppe = scraper.get_with_nl("http://www.lachambre.be/kvvcr/showpage.cfm?section=/comm/commissions&language=fr&cfm=/site/wwwcfm/comm/LstCom.cfm&rightmenu=right_cricra", "commissions list")
        _type = ""
        for i, j in zip(soup("div", id="story")[1], suppe("div", id="story")[1]):
            if not isinstance(i, NavigableString) and (i.h4 or i.a):
                if i.h4:
                    _type = i.h4.text
                    _type_nl = j.h4.text
                elif i.a:
                    commission = get_or_create(Commission, lachambre_id=int(re.search("com=(\d+)", i.a["href"]).groups()[0]))
                    commission.type["fr"] = _type
                    commission.type["nl"] = _type_nl
                    commission.name["fr"] = i.a.text
                    commission.name["nl"] = j.a.text
                    commission.url = i.a["href"]

                    commission.save()

        for com in list(Commission.objects.all()):
            klass.fetch_one(com, cache=cache, sync=sync)

    @classmethod
    def fetch_one(klass, commission, cache=False, sync=False):
        soup, suppe = scraper.get_with_nl(LACHAMBRE_PREFIX + commission.url, "commission %s" % commission.lachambre_id)
        commission.full_name["fr"] = soup.h1.text
        commission.full_name["nl"] = suppe.h1.text
        commission.deputies = []
        seats = {"fr": {}, "nl": {}}
        for i, j in zip(soup('p')[2:], suppe('p')[2:]):
            role = i.b.text[:-1]
            role_nl = j.b.text[:-1]
            for dep in i('a'):
                deputy = Deputy.objects.get(lachambre_id=re.search("key=([O0-9]+)", dep["href"]).groups()[0])
                membership = get_or_create(CommissionMembership, deputy=deputy, commission=commission)
                membership.role = role

lachambre/views.py
# Create your views here.

templates/lachambre/analysis_detail.html
{% extends "object_display.html" %}

templates/lachambre/analysis_list.html
{% extends "base.html" %}

{% block title %}
<h1>Analysis</h1>
{% endblock %}

{% block content %}
<div style="padding-top: 10px;" class="page-header">
    <h1>List</h1>
</div>

<ul>
{% for analysis in object_list %}
    <li><a href="{% url 'deputies:analysis' analysis.lachambre_id %}">{{ analysis.lachambre_id }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/lachambre/annualreport_list.html
{% extends "base.html" %}

{% block title %}
<h1>Annual reports</h1>
{% endblock %}

{% block content %}
<div style="padding-top: 10px;" class="page-header">
    <h1>List of available annual reports</h1>
</div>

<ul>
{% for report in object_list %}
    <li><a href="{% url 'deputies:annual-report' report.id %}">{{ report.id }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/lachambre/commission_detail.html
{% extends "object_display.html" %}

templates/lachambre/commission_list.html
{% extends "base.html" %}

{% block title %}
<h1>Commissions</h1>
{% endblock %}

{% block content %}
<div style="padding-top: 10px;" class="page-header">
    <h1>List of available documents</h1>
</div>

<ul>
{% for commission in object_list %}
    <li><a href="{% url 'deputies:commission' commission.lachambre_id %}">{{ commission.lachambre_id }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/lachambre/commissionmembership_list.html
{% extends "base.html" %}

{% block title %}
<h1>Commissions</h1>
{% endblock %}

{% block content %}
<div style="padding-top: 10px;" class="page-header">
    <h1>List of available documents</h1>
</div>

<ul>
{% for commission_membership in object_list %}
  <li><a href="{% url 'deputies:commission-membership' commission_membership.pk %}">[{{ commission_membership.commission.name.fr }} / {{ commission_membership.commission.name.nl }}] - {{ commission_membership.deputy.full_name }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/lachambre/deputy_list.html
{% extends "base.html" %}

{% block title %}
<h1>Deputies</h1>
{% endblock %}

{% block content %}
<div style="padding-top: 10px;" class="page-header">
    <h1>List of available documents</h1>
</div>

<ul>
{% for deputy in object_list %}
    <li><a href="{% url 'deputies:deputy' deputy.lachambre_id %}">{{ deputy.full_name }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/lachambre/document_detail.html
{% extends "object_display.html" %}

templates/lachambre/document_list.html
{% extends "base.html" %}

{% block title %}
<h1>Documents</h1>
{% endblock %}

{% block content %}
<div style="padding-top: 10px;" class="page-header">
    <h1>List of available documents</h1>
</div>

<ul>
{% for document in object_list %}
    <li><a href="{% url 'deputies:document' document.lachambre_id %}">{{ document.lachambre_id }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/lachambre/party_detail.html
{% extends "object_display.html" %}

templates/lachambre/party_list.html
{% extends "base.html" %}

{% block title %}
<h1>Parties</h1>
{% endblock %}

{% block content %}
<div style="padding-top: 10px;" class="page-header">
    <h1>List of available documents</h1>
</div>

<ul>
{% for party in object_list %}
    <li><a href="{% url 'deputies:party' party.id %}">{{ party.name }}</a></li>
{% endfor %}
</ul>
{% endblock %}

templates/lachambre/question_detail.html
{% extends "object_display.html" %}

templates/lachambre/writtenquestion_detail.html
{% extends "object_display.html" %}

templates/lachambre/writtenquestion_list.html
{% extends "base.html" %}

{% block title %}
<h1>Written Questions</h1>
{% endblock %}

{% block content %}
<div style="padding-top: 10px;" class="page-header">
    <h1>List of available documents</h1>
</div>

<ul>
{% for question in object_list %}
    <li><a href="{% url 'deputies:written-question' question.lachambre_id %}">{{ question.lachambre_id }}</a></li>
{% endfor %}
</ul>
{% endblock %}