dierentheater/urls.py
#  Dieren Theater - lachambre.be to json sausage machine
#  Copyright (C) 2011  Laurent Peuch <cortex@worlddomination.be>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import patterns, include, url
from django.views.generic import TemplateView

from tastypie.api import Api
from lachambre.api import DeputyResource, PartyResource, CommissionMembershipRessource, CommissionResource, DocumentResource, WrittenQuestionResource, AnnualReportRessource

v1_api = Api(api_name='v1')
v1_api.register(AnnualReportRessource())
v1_api.register(DeputyResource())
v1_api.register(PartyResource())
v1_api.register(CommissionResource())
v1_api.register(CommissionMembershipRessource())
v1_api.register(DocumentResource())
v1_api.register(WrittenQuestionResource())

# Uncomment the next two lines to enable the admin:
# from django.contrib import admin
# admin.autodiscover()

urlpatterns = patterns('',
    url(r'^$', TemplateView.as_view(template_name="home.html"), name='home'),
    url(r'^lachambre/', include('lachambre.urls', namespace='deputies')),
    url(r'^api/', include(v1_api.urls)),
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),
    # url(r'^admin/', include(admin.site.urls)),
)

lachambre/urls.py
#  Dieren Theater - lachambre.be to json sausage machine
#  Copyright (C) 2011  Laurent Peuch <cortex@worlddomination.be>
#
#  This program is free software: you can redistribute it and/or modify
#  it under the terms of the GNU Affero General Public License as
#  published by the Free Software Foundation, either version 3 of the
#  License, or any later version.
#
#  This program is distributed in the hope that it will be useful,
#  but WITHOUT ANY WARRANTY; without even the implied warranty of
#  MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
#  GNU Affero General Public License for more details.
#
#  You should have received a copy of the GNU Affero General Public License
#  along with this program.  If not, see <http://www.gnu.org/licenses/>.

from django.conf.urls.defaults import patterns, url
from django.views.generic import ListView, DetailView

from models import Deputy, Party, Commission, Document, Question, Analysis, WrittenQuestion, AnnualReport, CommissionMembership

urlpatterns = patterns('',
    url(r'^deputy/$', ListView.as_view(queryset=Deputy.objects.all()), name='deputy-list'),
    # yes, O in the regex, one deputy has an O instead of a 0 in it's lachambre_id, yes this is awfull
    url(r'^deputy/(?P<slug>[O0-9]+)/$', DetailView.as_view(queryset=Deputy.objects.all(), slug_field="lachambre_id"), name='deputy'),
    url(r'^party/$', ListView.as_view(queryset=Party.objects.all()), name='party-list'),
    url(r'^party/(?P<pk>[-a-zA-Z0-9]+)/$', DetailView.as_view(queryset=Party.objects.all(), slug_field="lachambre_id"), name='party'),
    url(r'^commission/$', ListView.as_view(queryset=Commission.objects.all()), name='commission-list'),
    url(r'^commission/(?P<slug>[0-9]+)/$', DetailView.as_view(queryset=Commission.objects.all(), slug_field="lachambre_id"), name='commission'),
    url(r'^commission-membership/$', ListView.as_view(queryset=CommissionMembership.objects.all()), name='commission-membership-list'),
    url(r'^commission-membership/(?P<pk>[-a-zA-Z0-9]+)/$', DetailView.as_view(queryset=CommissionMembership.objects.all()), name='commission-membership'),
    url(r'^document/$', ListView.as_view(queryset=Document.objects.all()), name='document-list'),
    url(r'^document/(?P<slug>[0-9]+)/$', DetailView.as_view(queryset=Document.objects.all(), slug_field="lachambre_id"), name='document'),
    url(r'^written-question/$', ListView.as_view(queryset=WrittenQuestion.objects.all()), name='written-question-list'),
    url(r'^written-question/(?P<slug>[-a-zA-Z0-9]+)/$', DetailView.as_view(queryset=WrittenQuestion.objects.all(), slug_field="lachambre_id"), name='written-question'),
    url(r'^question/$', ListView.as_view(queryset=Question.objects.all()), name='question-list'),
    url(r'^question/(?P<slug>[A-Z0-9]+)/$', DetailView.as_view(queryset=Question.objects.all(), slug_field="lachambre_id"), name='question'),
    url(r'^analysis/$', ListView.as_view(queryset=Analysis.objects.all()), name='analysis-list'),
    url(r'^analysis/(?P<slug>[A-Z0-9]+)/$', DetailView.as_view(queryset=Analysis.objects.all(), slug_field="lachambre_id"), name='analysis'),
    url(r'^annual-report/$', ListView.as_view(queryset=AnnualReport.objects.all()), name='annual-report-list'),
    url(r'^annual-report/(?P<pk>[-a-zA-Z0-9]+)/$', DetailView.as_view(queryset=AnnualReport.objects.all()), name='annual-report'),
)

templates/base.html
<!DOCTYPE html>
<html>
    <head>
        <title>Dieren Theater</title>
        <link rel="stylesheet" href="/static/css/bootstrap/bootstrap.min.css">
        <link rel="stylesheet" href="/static/css/bootstrap/docs.css">
    </head>
    <body>
        <div class="topbar" data-scrollspy="scrollspy" >
          <div class="topbar-inner">
            <div class="container">
              <a class="brand" href="{% url 'home' %}">Dieren Theater</a>

              <ul class="nav">
                <li><a href="{% url 'deputies:deputy-list' %}">Deputies</a></li>
                <li><a href="{% url 'deputies:party-list' %}">Parties</a></li>
                <li><a href="{% url 'deputies:commission-list' %}">Commissions</a></li>
                <li><a href="{% url 'deputies:document-list' %}">Law projects or texts</a></li>
                <li><a href="{% url 'deputies:written-question-list' %}">Written questions</a></li>
                <li><a href="{% url 'deputies:annual-report-list' %}">Annual reports</a></li>
              </ul>
            </div>
          </div>
        </div>
        <header id="overview" class="jumbotron masthead">
            <div class="inner">
                <div class="container">
                    {% block title %}
                    {% endblock %}
                </div>
            </div>
        </header>
        <div class="quickstart">
            <div class="container">
                {% block quickstart %}
                <p></p>
                {% endblock %}
            </div>
        </div>
        <div class="container">
            {% block content %}
            {% endblock %}
        </div>
        <footer class="footer">
            <div class="container">
                <p>Dieren Theater is freesoftware licenced under aGPLv3+, you can find the code <a href="https://github.com/Psycojoker/dierentheater">here</a>.</p>
            </div>
        </footer>
    </body>
</html>

templates/home.html
{% extends 'base.html' %}

{% block title %}
<h1>Dieren Theater</h1>
<p class="lead">
Dieren Theater is a project to create a lachambre.be_to_json sausage machine<br>
The objective is to bring to us citizen opendata.
</p>

<p>
It's a free software licenced under aGPLv3+, you can find the code <a href="https://github.com/Psycojoker/dierentheater">here</a>. You can report bugs <a href="https://github.com/Psycojoker/dierentheater/issues">here</a>.<br>

So far, this is only my personal initiative.
</p>
{% endblock %}

{% block content %}

<div class="alert-message warning" style="margin-top: 15px">
    <p><span  style="text-decoration: line-through;">Due to the combination of LaChambre/DeKamer.be chaging it's interface and the lost of the hard drive of the previous server, most of the data is currently unavailable until I fix the parsers. I'm sorry about that.</span> Most parsers are fixed now, only the Law projects one still need work.</p>
    <br>
    <p>If you need specifics data, don't hesitate to <a href="mailto:brain at worlddomination dot be">contact me</a>, I'm busy on a lot of projects and activites and DierenTheater isn't in the top of my priority list so this will help me prioritising.</p>
</div>

<div class="page-header">
    <h1>News</h1>
</div>
<ul>
    <li><b>2014-05-16</b>: finally took the time to fix most of the parsers, still need to fix the law text one. Dumps are available again (except the law text one obviously).
    </li>
    <li><b>2013-12-09</b>:
    <ul>
        <li><a href="{% url "deputies:party-list" %}">parties</a> are now available in the API (but don't expect a lot of data).</li>
        <li>"<i>Other data</i>" section has been added (see below).</li>
    </ul>
    </li>
    <li><b>2013-12-08</b>: after a server problem, DierenTheater is up again \o/</li>
</ul>

<div class="page-header">
    <h1>Introduction</h1>
</div>
<p>Well hello there, welcome to Dieren Theater!</p>
<p>Right now you are probably asking yourself a legitimate question, what is Dieren Theater? Dieren Theater is a project to offer to anyone structured and open data extracted (in fact scraped) from the website of the Belgian parliament (also knows as La Chambre or De Kamer).</p>
<p>Again, you might are asking yourself "Why? What is the meaning of that?". Well in fact, open data is one of the first step for us citizens to appropriate ourself political informations (political as in « the life of the city »), the way it is treated and displayed, to move from passive consumer to active creator and to get involved in this democratic process.</p>
<p>Sound too theoretical? Lets me show you some example:</p>
<ul>
    <li><a href="http://www.nosdeputes.fr/">Nos Députés.fr</a> and <a href="http://www.nossenateurs.fr/">Nos Sénateurs.fr</a> (both in french), two website from <a href="http://www.regardscitoyens.org/">Regards Citoyens</a> (a citizen group) that allow us to see the activities of the French deputies and senators, the subject they are the most working on, their interventions and many others informations. Those informations wasn't displayed in that what at all on the French parliament website.</li>
    <li><a href="http://memopol.lqdn.fr">The Political Memory</a> (English) which is a tool that allow an organization (here <a href="http://laquadrature.net">La Quadrature du Net</a>) to put online the voting recommendations they have been sending to elected representatives (here deputies of the European Parliament and French deputies) and show who is following their recommendations the best. This allow here for example to see which elected representatives is the more for Fundamental Freedoms, Net Neutrality and other in the sens that defend la Quadrature du Net.</li>
    <li><a href="http://pippi.euwiki.org/">Pippi Longstrings</a> (English) which is a tool to do text analysis on European Laws related documents and to see for example (but not only) which documents have text in common</li>
    <li><a href="http://parltrack.euwiki.org">Parltrack</a> (English) which allows to track the legislative work of the European Parliament especially by following dossiers and/or committees.</li>
    <li><a href="http://coulmont.com/blog/2011/09/02/travail-de-deputes/">An interesting visualisation</a> (French) by <a href="http://coulmont.com/">Baptise Coulmont</a> which display the relations betweens French deputies based on how often they have been working together (by proposing laws).</li>
</ul>
<p>None of those would have been possible without data and none of this has yet happen (in my knowledge) in Belgium. So Dieren Theater is an attempt to build the first step by providing data to everyone and therefor allowing everyone to build similar tools or analysis.</p>
<p>It is interesting to notes that (except Baptise Coulmont works) all of these website are Free software (as in speech).</p>
<div style="padding-top: 15px;" class="page-header">
    <h1>Current state of the project</h1>
</div>
<p>For the moment this project can be considered as an <span class="label important">alpha</span>, not because it is unstable be because it is very young, that a part of the data is missing (not already scraped) and that the available data (you have a list bellow) will probably needs polishing.</p>
<h3>Roadmap <small>(aka thing that I think I'm going to do)</small></h3>
<ul>
    <li>get more data, obviously</li>
    <li>but sooner having an intelligent automatic update strategy of data to avoid doing a sequential parse every night</li>
    <li>storing an history of the modifications of every data</li>
    <li>...</li>
    <li>PROFIT</li>
</ul>
<p>I'm looking for <span class="label warning">feedback</span> on the data from people that are trying to build or play with it. Don't hesitate to <span class="label notice"><a href="mailto://laurent@nurpa.be">contact me</a></span> or to <span class="label notice"><a href="https://github.com/Psycojoker/dierentheater/issues/new">open a ticket</a></span> on the bug tracker.</p>
<p>In a long term it is totally possible to think of parsing other similar websites than (lachambre|dekamer).be (like the senate website).</p>
<div style="padding-top: 15px;" class="page-header">
    <h1>List of parsed data</h1>
</div>
<p><span class="label notice">Info</span> those links point you to a web interface that gives you an idea of the available data and their format, to get the actual data use the API bellow.</p>
<p><span class="label warning">Warning</span> small differences between the data displayed on the web interface and the data get from the API is possible. If you notice this situation, <b><a href="https://github.com/Psycojoker/dierentheater/issues/new">please report a bug</a></b>.</p>
<div class="row">
    <div class="span5">
        <h2>Available documents</h2>
        <ul>
            <li><a href="{% url 'deputies:deputy-list' %}">Deputies</a></li>
            <li><a href="{% url 'deputies:party-list' %}">Parties</a></li>
            <li><a href="{% url 'deputies:commission-list' %}">Commissions</a></li>
            <li><a href="{% url 'deputies:commission-membership-list' %}">Commissions Membership</a> (of deputies)</li>
            <li><a href="{% url 'deputies:document-list' %}">Law projects/texts</a></li>
            <li><a href="{% url 'deputies:written-question-list' %}">Written questions</a></li>
            <li><a href="{% url 'deputies:annual-report-list' %}">Annual reports</a></li>
        </ul>
    </div>
    <div class="span5">
        <h2><acronym title="Work In Progress">WIP</acronym> documents</h2>
        <ul>
            <li><a href="{% url 'deputies:question-list' %}">Others questions</a></li>
            <li><a href="{% url 'deputies:analysis-list' %}">Analysis</a></li>
        </ul>
    </div>
    <div class="span5">
        <h2>Planned documents</h2>
        <ul>
            <li>Commissions agenda</li>
        </ul>
    </div>
</div>

<div style="padding-top: 15px;" class="page-header">
    <h1>Other Data</h1>
</div>

<p>Some other data generated by me or given to me. As the rest of the data, everything is licenced under the ODbL.</p>

<ul>
    <li>A <a href="https://sqlite.org/">sqlite</a> database of a dump of the written questions. Generated by <a href="https://github.com/Psycojoker/dierentheater_wq_to_sqlite">this script</a>. <a href="/static/other/question.db.xz">Download</a> (warning: compressed in .xz)</li>
</ul>

<div style="padding-top: 15px;" class="page-header">
    <h1>Dumps</h1>
</div>

<p>As requested by some persons, here are dump of each collections of the database. All data are in <span class="label info">json</span> since it's coming from mongoDB. For bandwidth reason I'm compressing them using <a href="http://tukaani.org/xz/">xz</a>:</p>
<ul>
    <li><a href="/static/dumps/deputy.xz">Deputies</a></li>
    <li><a href="/static/dumps/commission.xz">Commissions</a></li>
    <li><a href="/static/dumps/commissionmembership.xz">Commissions membership</a></li>
    <li><a href="/static/dumps/document.xz" style="text-decoration: line-through">Law projects/texts</a> (bad data for now)</li>
    <li><a href="/static/dumps/writtenquestion.xz">Written questions</a></li>
    <li><a href="/static/dumps/annualreport.xz">Annual reports</a></li>
</ul>

<div style="padding-top: 15px;" class="page-header">
    <h1>API <small>where the fun begins</small></h1>
</div>
<p>Okay, lets start funny things, how to get data!</p>
<p>Everything starts here:</p>
<pre><a href="http://dierentheater.be/api/v1/?format=json">http://dierentheater.be/api/v1/?format=json</a></pre>
<p>And in a more convenient way (in a shell if you are using an unix based operating system):</p>
<pre>curl "<a href="http://dierentheater.be/api/v1/?format=json">http://dierentheater.be/api/v1/?format=json</a>" | python -m json.tool</pre>
<p>The API is self describing so I won't write a lot here about the data in it. If you want to have and idea of what is available just browse it via the links in the previous section.</p>
<p>An interesting possibility of the API is that you can add the GET argument "<i>lachambre_id</i>" to the url to query an exact data like this:</p>
<pre>curl "<a href="http://dierentheater.be/api/v1/document/?format=json&lachambre_id=2005">http://dierentheater.be/api/v1/document/?format=json&lachambre_id=2005</a>" | python -m json.tool</pre>
<p><b>Always use this way a querying an individual document whenever possible if you want to build something that is supposed to last</b>, the <i>id</i> field (coming from mongoDB) <b>isn't reliable at all</b> for the moment.</p>

<p>You can find tastypie API <b>documentation</b> <a href="http://django-tastypie.readthedocs.org/en/latest/interacting.html#fetching-data">here</a></p>

<p>Available formats are <a href="https://en.wikipedia.org/wiki/Json"><span class="label success">json</span></a>, <a href="https://en.wikipedia.org/wiki/Xml"><span class="label success">xml</span></a> and <a href="https://en.wikipedia.org/wiki/Yaml"><span class="label success">yaml</span></a> (just replace <i>json</i> with <i>xml</i> or <i>yaml</i> in the url).</p>
<p>I hope you'll have fun playing with it!</p>
<div style="padding-top: 15px;" class="page-header">
    <h1>Technical details</h1>
</div>
<p>This website is build in <a href="http://www.python.org/">Python</a>, using <a href="http://django-mongoDB.org/">django-nonrel</a>, a fork of <a href="https://www.djangoproject.com/">django</a> to use <a href="http://www.mongodb.org/">mongoDB</a> instead of a SQL database. Parsing is done using the very awesome <a href="http://www.crummy.com/software/BeautifulSoup/">BeautifulSoup</a> with long sessions under <a href="http://ipython.org/">IPython</a>. The API is done with a <a href="https://github.com/Psycojoker/django-tastypie-nonrel">patched version</a> of <a href="https://github.com/andresdouglas/django-tastypie-nonrel">tastypie-nonrel</a>. And I use <a href="http://twitter.github.com/bootstrap/">boostrap</a> to make you believe that I know how to do a pretty website.</p>
<div style="padding-top: 15px;" class="page-header">
    <h1>Get involved!</h1>
</div>
<p>So you want to help? Well thanks a lot for your proposition!</p>
<p>So, how can you do this?</p>
<ul>
    <li>well, the first obvious way to help this project is to spread the love, this project doesn't make any sens if nobody builds things out of it so talk about it to everyone you know that is likely to do so!</li>
    <li>the second obvious way to help is to build cool things out of it! Send me an email if you do so, this will boost my motivation.</li>
    <li>the third way is to get involved technically in the project, the used technologies are listed above and the code is <a href="https://github.com/Psycojoker/dierentheater">here</a>. Fork the depot and send me a pull request. If you are planning on doing something a bit big it's a very idea that we talk about it before to avoid you going in the bad direction.</li>
    <li>and there are surely many other ways to help, I'm counting on you to be creative!</li>
</ul>
<div style="padding-top: 15px;" class="page-header">
    <h1>Licence</h1>
</div>
<p>All data provided by this website is licenced under the <a href="http://opendatacommons.org/licenses/odbl/">Open Data Commons Open Database License (ODbL)</a> also known as the "CC-BY-SA of databases".</p>
<p>The <a href="https://github.com/Psycojoker/dierentheater">code</a> of this website is licenced under the <a href="https://www.gnu.org/licenses/agpl-3.0.html">aGPLv3+</a>.</p>
{% endblock %}

templates/object_display.html
{% extends "base.html" %}

{% block title %}
    <h2 style="color: #FFFFFF; text-shadow: 0 1px 2px rgba(0, 0, 0, 0.5);">{{ object }}</h2>
{% endblock %}

{% block content %}
<div style="padding-top: 10px;" class="page-header">
    <h1>Json document</h1>
</div>

{% block documentation %}
{% endblock %}

<pre>{{ object.json }}</pre>

{% if object.get_url %}
<div style="text-align: center; padding-top: 20px; padding-bottom: 20px;">
    <p><a class="btn info" href="{{ object.get_url }}">Page on lachambre.be</a></p>
</div>
{% endif %}
{% endblock %}